# Generated by Django 3.0.10 on 2021-05-25 08:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resturaunt_Day_Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('totalNo', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'tbl_resturaunt_day_meal',
            },
        ),
        migrations.CreateModel(
            name='Resturaunt_Guest_Day_Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Department_ResturaunGuestDayMeal', to='baseInfo.Department')),
            ],
            options={
                'db_table': 'tbl_resturaunt_guest_day_meal',
            },
        ),
        migrations.CreateModel(
            name='Resturaunt_Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.FileField(null=True, upload_to='meal_pix')),
            ],
            options={
                'db_table': 'tbl_resturaunt_meal',
            },
        ),
        migrations.CreateModel(
            name='Resturaunt_Guest_Day_Meal_Junction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField()),
                ('resturaunt_day_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ResturauntDayMeal_ResturauntGuestDayMealJunction', to='resturaunt.Resturaunt_Day_Meal')),
                ('resturaunt_guest_day_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ResturauntGuestDayMeal_ResturauntGuestDayMealJunction', to='resturaunt.Resturaunt_Guest_Day_Meal')),
            ],
            options={
                'db_table': 'tbl_resturaunt_guest_day_meal_junction',
                'unique_together': {('resturaunt_day_meal', 'resturaunt_guest_day_meal')},
            },
        ),
        migrations.AddField(
            model_name='resturaunt_guest_day_meal',
            name='resturaunt_day_meals',
            field=models.ManyToManyField(through='resturaunt.Resturaunt_Guest_Day_Meal_Junction', to='resturaunt.Resturaunt_Day_Meal'),
        ),
        migrations.CreateModel(
            name='Resturaunt_Employee_Day_Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('served', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employee_ResturauntEmployeeDayMeal', to='baseInfo.Employee')),
                ('resturaunt_day_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ResturauntDayMeal_ResturauntEmployeeDayMeal', to='resturaunt.Resturaunt_Day_Meal')),
            ],
            options={
                'db_table': 'tbl_resturaunt_employee_day_meal',
            },
        ),
        migrations.AddField(
            model_name='resturaunt_day_meal',
            name='resturaunt_meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ResturauntMeal_ResturauntDayMeal', to='resturaunt.Resturaunt_Meal'),
        ),
        migrations.AlterUniqueTogether(
            name='resturaunt_day_meal',
            unique_together={('resturaunt_meal', 'date')},
        ),
    ]
