# Generated by Django 3.0.10 on 2021-07-31 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0002_auto_20210731_1619'),
        ('resturaunt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturaunt_guest_day_meal',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Project_ResturaunGuestDayMeal', to='baseInfo.Project'),
        ),
        migrations.AlterField(
            model_name='resturaunt_employee_day_meal',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Employee_ResturauntEmployeeDayMeal', to='baseInfo.Employee'),
        ),
        migrations.AlterField(
            model_name='resturaunt_employee_day_meal',
            name='resturaunt_day_meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ResturauntDayMeal_ResturauntEmployeeDayMeal', to='resturaunt.Resturaunt_Day_Meal'),
        ),
        migrations.AlterField(
            model_name='resturaunt_guest_day_meal',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Department_ResturaunGuestDayMeal', to='baseInfo.Department'),
        ),
        migrations.AlterField(
            model_name='resturaunt_guest_day_meal_junction',
            name='resturaunt_day_meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ResturauntDayMeal_ResturauntGuestDayMealJunction', to='resturaunt.Resturaunt_Day_Meal'),
        ),
        migrations.AlterField(
            model_name='resturaunt_guest_day_meal_junction',
            name='resturaunt_guest_day_meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ResturauntGuestDayMeal_ResturauntGuestDayMealJunction', to='resturaunt.Resturaunt_Guest_Day_Meal'),
        ),
    ]
