# Generated by Django 3.0.10 on 2021-08-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturaunt', '0002_auto_20210731_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturaunt_day_meal',
            name='isActive',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
