# Generated by Django 3.0.10 on 2021-08-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturaunt', '0003_resturaunt_day_meal_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturaunt_day_meal',
            name='monthID',
            field=models.SmallIntegerField(null=True),
        ),
    ]
