# Generated by Django 3.0.10 on 2021-05-25 08:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'tbl_survey_answer',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=500)),
                ('questionType', models.PositiveSmallIntegerField()),
                ('isRequired', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_survey_question',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('expired_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('description', models.CharField(max_length=500)),
                ('surveyType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SurveyType_Survey', to='baseInfo.SurveyType')),
            ],
            options={
                'db_table': 'tbl_survey_survey',
            },
        ),
        migrations.CreateModel(
            name='User_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortAnswer', models.CharField(blank=True, max_length=200)),
                ('paragraph', models.CharField(blank=True, max_length=1000)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Answer_UserAnswer', to='surveys.Answer')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Question_UserAnswer', to='surveys.Question')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_UserAnswers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_survey_user_answer',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Survay_Question', to='surveys.Survey'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Question_Answer', to='surveys.Question'),
        ),
        migrations.CreateModel(
            name='SurveyDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Department_SurveyDepartment', to='baseInfo.Department')),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Survey_SurveyDepartment', to='surveys.Survey')),
            ],
            options={
                'db_table': 'tbl_survey_department',
                'unique_together': {('department', 'survey')},
            },
        ),
    ]
