# Generated by Django 3.0.10 on 2021-05-29 08:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocAppointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('canceled', models.BooleanField(default=False)),
                ('passed', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_doc_appointments',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitDuration', models.PositiveSmallIntegerField(null=True)),
                ('doctorType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DoctorType_Doctor', to='baseInfo.DoctorType')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Employee_Doctor', to='baseInfo.Employee')),
            ],
            options={
                'db_table': 'tbl_doctors',
            },
        ),
        migrations.CreateModel(
            name='DocSchedulesWeekDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.PositiveSmallIntegerField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Doctor_ScheduleWeekDays', to='doctor_appointments.Doctors')),
            ],
            options={
                'db_table': 'tbl_doc_schedule_weekdays',
            },
        ),
        migrations.CreateModel(
            name='DocSchedulesDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('visitDuration', models.PositiveSmallIntegerField()),
                ('schedulesWeekDay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ScheduleWeekDay_ScheduleDays', to='doctor_appointments.DocSchedulesWeekDays')),
            ],
            options={
                'db_table': 'tbl_doc_schedule_days',
            },
        ),
        migrations.CreateModel(
            name='DocPatientsFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileTitle', models.CharField(blank=True, max_length=150)),
                ('file', models.FileField(null=True, upload_to='patient_files')),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Appointment_PatientFile', to='doctor_appointments.DocAppointments')),
            ],
            options={
                'db_table': 'tbl_doc_patients_files',
            },
        ),
        migrations.CreateModel(
            name='DocPatients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Doctors_Patient', to='doctor_appointments.Doctors')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Employees_Patient', to='baseInfo.Employee')),
            ],
            options={
                'db_table': 'tbl_doc_patients',
            },
        ),
        migrations.CreateModel(
            name='DocAppointmentTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserveNo', models.PositiveSmallIntegerField()),
                ('reserveTime', models.TimeField()),
                ('schedulesDay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Scheduleday_Appointmenttime', to='doctor_appointments.DocSchedulesDays')),
            ],
            options={
                'db_table': 'tbl_doc_appointment_times',
            },
        ),
        migrations.AddField(
            model_name='docappointments',
            name='appointmentTime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Appointmenttime_Appointment', to='doctor_appointments.DocAppointmentTimes'),
        ),
        migrations.AddField(
            model_name='docappointments',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Doctor_Appointment', to='doctor_appointments.Doctors'),
        ),
        migrations.AddField(
            model_name='docappointments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_Appointment', to=settings.AUTH_USER_MODEL),
        ),
    ]
