# Generated by Django 3.0.10 on 2021-07-31 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Company_Department', to='baseInfo.Company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Department_Employee', to='baseInfo.Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='jobPosition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='JobPosition_Employee', to='baseInfo.JobPosition'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Project_Employee', to='baseInfo.Project'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Company_Project', to='baseInfo.Company'),
        ),
    ]
