# Generated by Django 3.0.10 on 2021-05-25 08:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting_Cater_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_meeting_cater_type',
            },
        ),
        migrations.CreateModel(
            name='Meeting_Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_meeting_equipment',
            },
        ),
        migrations.CreateModel(
            name='Meeting_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'tbl_meeting_request',
            },
        ),
        migrations.CreateModel(
            name='Meeting_Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_meeting_room',
            },
        ),
        migrations.CreateModel(
            name='Meeting_Room_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_meeting_room_type',
            },
        ),
        migrations.CreateModel(
            name='Meeting_Room_Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=500)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='meeting_request.Meeting_Equipment')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='meeting_request.Meeting_Room')),
            ],
            options={
                'db_table': 'tbl_meeting_room_equipment',
                'unique_together': {('room', 'equipment')},
            },
        ),
        migrations.AddField(
            model_name='meeting_room',
            name='equipments',
            field=models.ManyToManyField(related_name='equipments', through='meeting_request.Meeting_Room_Equipment', to='meeting_request.Meeting_Equipment'),
        ),
        migrations.AddField(
            model_name='meeting_room',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_type', to='meeting_request.Meeting_Room_Type'),
        ),
        migrations.CreateModel(
            name='Meeting_Request_Cater_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('cater_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cater_type', to='meeting_request.Meeting_Cater_Type')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='meeting_request.Meeting_Request')),
            ],
            options={
                'db_table': 'tbl_meeting_request_cater_type',
                'unique_together': {('request', 'cater_type')},
            },
        ),
        migrations.AddField(
            model_name='meeting_request',
            name='cater_types',
            field=models.ManyToManyField(related_name='cater_types', through='meeting_request.Meeting_Request_Cater_Type', to='meeting_request.Meeting_Cater_Type'),
        ),
        migrations.AddField(
            model_name='meeting_request',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='baseInfo.Department'),
        ),
        migrations.AddField(
            model_name='meeting_request',
            name='meeting_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='romm', to='meeting_request.Meeting_Room'),
        ),
        migrations.AddField(
            model_name='meeting_request',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='baseInfo.Employee'),
        ),
    ]
