# Generated by Django 3.0.10 on 2021-04-28 08:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting_Cater_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_meeting_cater_type',
            },
        ),
        migrations.CreateModel(
            name='Meeting_Necessary_Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_meeting_necessary_equipment',
            },
        ),
        migrations.CreateModel(
            name='Meeting_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('personel_no', models.PositiveSmallIntegerField()),
                ('cater_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_request_cater_type', to='meeting_request.Meeting_Cater_Type')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_meeting_request', to='baseInfo.Employee')),
                ('necessary_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_request_necessary_equipment', to='meeting_request.Meeting_Necessary_Equipment')),
            ],
            options={
                'db_table': 'tbl_meeting_request',
            },
        ),
    ]
