# Generated by Django 3.0.10 on 2021-06-16 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting_request_cater_type',
            name='cater_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_cater_type_cater_type', to='meeting_request.Meeting_Cater_Type'),
        ),
        migrations.AlterField(
            model_name='meeting_request_cater_type',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_cater_type_request', to='meeting_request.Meeting_Request'),
        ),
        migrations.AlterField(
            model_name='meeting_room',
            name='equipments',
            field=models.ManyToManyField(related_name='room_equipments', through='meeting_request.Meeting_Room_Equipment', to='meeting_request.Meeting_Equipment'),
        ),
        migrations.AlterField(
            model_name='meeting_room_equipment',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_equipment_equipment', to='meeting_request.Meeting_Equipment'),
        ),
        migrations.CreateModel(
            name='Meeting_Request_Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField(null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_equipment_equipment', to='meeting_request.Meeting_Equipment')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_equipment_request', to='meeting_request.Meeting_Request')),
            ],
            options={
                'db_table': 'tbl_meeting_request_equipment',
                'unique_together': {('request', 'equipment')},
            },
        ),
        migrations.AddField(
            model_name='meeting_request',
            name='equipments',
            field=models.ManyToManyField(related_name='request_equipments', through='meeting_request.Meeting_Request_Equipment', to='meeting_request.Meeting_Equipment'),
        ),
    ]
