# Generated by Django 3.0.10 on 2021-05-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting_equipment',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meeting_request_cater_type',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='meeting_room_equipment',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='meeting_room_equipment',
            name='qty',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
