# Generated by Django 3.0.10 on 2021-05-12 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting_Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_meeting_room',
            },
        ),
        migrations.RenameField(
            model_name='meeting_request',
            old_name='employee',
            new_name='requester',
        ),
        migrations.RemoveField(
            model_name='meeting_request',
            name='cater_type',
        ),
        migrations.RemoveField(
            model_name='meeting_request',
            name='necessary_equipment',
        ),
        migrations.RemoveField(
            model_name='meeting_request',
            name='personel_no',
        ),
        migrations.AddField(
            model_name='meeting_request',
            name='cater_types',
            field=models.ManyToManyField(related_name='cater_types', to='meeting_request.Meeting_Cater_Type'),
        ),
        migrations.AddField(
            model_name='meeting_request',
            name='necessary_equipments',
            field=models.ManyToManyField(related_name='necessary_equipments', to='meeting_request.Meeting_Necessary_Equipment'),
        ),
        migrations.AddField(
            model_name='meeting_request',
            name='meeting_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_room_meeting_request', to='meeting_request.Meeting_Room'),
            preserve_default=False,
        ),
    ]
