# Generated by Django 3.0.10 on 2021-05-15 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_request', '0002_auto_20210512_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting_request',
            name='cater_types',
        ),
        migrations.RemoveField(
            model_name='meeting_request',
            name='necessary_equipments',
        ),
        migrations.DeleteModel(
            name='Meeting_Cater_Type',
        ),
        migrations.DeleteModel(
            name='Meeting_Necessary_Equipment',
        ),
    ]
