# Generated by Django 3.0.10 on 2021-05-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_request', '0002_auto_20210525_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting_request',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
