# Generated by Django 3.0.10 on 2021-06-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_request', '0002_auto_20210616_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting_request',
            name='meeting_member_no',
            field=models.PositiveSmallIntegerField(default=30),
            preserve_default=False,
        ),
    ]
