# Generated by Django 3.0.10 on 2021-05-15 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0001_initial'),
        ('meeting_request', '0003_auto_20210515_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting_Cater_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_meeting_cater_type',
            },
        ),
        migrations.CreateModel(
            name='Meeting_Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_meeting_equipment',
            },
        ),
        migrations.AlterField(
            model_name='meeting_request',
            name='meeting_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetingRoom_meetingRequest', to='meeting_request.Meeting_Room'),
        ),
        migrations.AlterField(
            model_name='meeting_request',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_meetingRequest', to='baseInfo.Employee'),
        ),
        migrations.AddField(
            model_name='meeting_request',
            name='cater_types',
            field=models.ManyToManyField(related_name='caterTypes_meetingRequest', to='meeting_request.Meeting_Cater_Type'),
        ),
        migrations.AddField(
            model_name='meeting_request',
            name='necessary_equipments',
            field=models.ManyToManyField(related_name='equipments_meetingRequest', to='meeting_request.Meeting_Equipment'),
        ),
    ]
