# Generated by Django 3.0.10 on 2021-06-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_request', '0003_meeting_request_meeting_member_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting_request',
            name='meeting_member_no',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
