# Generated by Django 3.0.10 on 2021-05-16 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseInfo', '0001_initial'),
        ('meeting_request', '0004_auto_20210515_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting_request',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employee_meetingRequest', to='baseInfo.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting_request',
            name='description',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
